tb_cart:
    path:     /cart/{id}/select
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:index" }

tb_cart_show:
    path:     /cart/{id}/show
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:show" }

tb_cart_list:
    path:     /cart/list
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:list" }

tb_cart_novo:
    path:     /cart/new
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:new" }

tb_cart_create:
    path:     /cart/create
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:create" }
    requirements: { _method: post }

tb_cart_edit:
    path:     /cart/{id}/edit
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:edit" }

tb_cart_update:
    path:     /cart/{id}/update
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:update" }
    requirements: { _method: post|put }

tb_cart_delete:
    path:     /cart/{id}/delete
    defaults: { _controller: "MsoftRCSystemBundle:TbCart:delete" }
    requirements: { _method: get }
