tb_client:
    path:     /client
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:index" }

tb_client_show:
    path:     /client/{id}/show
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:show" }

tb_client_new:
    path:     /client/new
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:new" }

tb_client_new_pdv:
    path:     /client/pdv/new
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:newPDV" }

tb_client_create:
    path:     /client/create
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:create" }
    requirements: { _method: post }

tb_client_edit:
    path:     /client/{id}/edit
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:edit" }

tb_client_update:
    path:     /client/{id}/update
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:update" }
    requirements: { _method: post|put }

tb_client_delete:
    path:     /client/{id}/delete
    defaults: { _controller: "MsoftRCSystemBundle:TbClient:delete" }
    requirements: { _method: post|delete|get }
