tb_deliver:
    path:     /deliver
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:index" }

tb_deliver_show:
    path:     /deliver/{id}/show
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:show" }

tb_deliver_new:
    path:     /deliver/new
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:new" }

tb_deliver_create:
    path:     /deliver/create
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:create" }
    requirements: { _method: post }

tb_deliver_edit:
    path:     /deliver/{id}/edit
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:edit" }

tb_deliver_update:
    path:     /deliver/{id}/update
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:update" }
    requirements: { _method: post|put }

tb_deliver_delete:
    path:     /deliver/{id}/delete
    defaults: { _controller: "MsoftRCSystemBundle:TbDeliver:delete" }
    requirements: { _method: post|delete }
