tb_payment_print:
    path:     /payment/print
    defaults: { _controller: "MsoftRCSystemBundle:TbPayment:print" }
    
tb_payment_filter:
    path:     /payment/filter
    defaults: { _controller: "MsoftRCSystemBundle:TbPayment:indexFilter" }
tb_payment:
    path:     /payment
    defaults: { _controller: "MsoftRCSystemBundle:TbPayment:index" }

tb_payment_show:
    path:     /payment/{id}/show
    defaults: { _controller: "MsoftRCSystemBundle:TbPayment:show" }



