tb_product_print:
    path:     /product/print
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:print" }
    
tb_product_nostock:
    path:     /product/nostock
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:noStock" }
    
tb_product:
    path:     /product
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:index" }

tb_product_show:
    path:     /product/{id}/show
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:show" }

tb_product_new:
    path:     /product/new
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:new" }

tb_product_create:
    path:     /product/create
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:create" }
    requirements: { _method: post }

tb_product_edit:
    path:     /product/{id}/edit
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:edit" }

tb_product_update:
    path:     /product/{id}/update
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:update" }
    requirements: { _method: post|put }

tb_product_delete:
    path:     /product/{id}/delete
    defaults: { _controller: "MsoftRCSystemBundle:TbProduct:delete" }
    requirements: { _method: post|delete }
