tb_stock:
    path:     /stock
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:index" }

tb_stock_new:
    path:     /stock/new
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:new" }
    
tb_stock_new_one:
    path:     /stock/add/{id}
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:newOne" }
    
tb_stock_confirm:
    path:     /stock/confirm/{id}
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:confirm" }

tb_stock_create:
    path:     /stock/create
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:create" }
    requirements: { _method: post }

tb_stock_edit:
    path:     /stock/{id}/edit/entry/{id_entry}
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:edit" }

tb_stock_update:
    path:     /stock/{id}/update
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:update" }
    requirements: { _method: post|put }

tb_stock_delete:
    path:     /stock/{id}/delete
    defaults: { _controller: "MsoftRCSystemBundle:TbStock:delete" }
    requirements: { _method: post|delete|get }
