<?php

namespace Msoft\RCSystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TbClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbClientRepository extends EntityRepository
{
}
