<?php

namespace Msoft\RCSystemBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * TbClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbProductRepository extends EntityRepository
{
    
    public function findByQuantity(){
//        $ezm = $this->getEntityManager();
//                $criteria = array()
$rsm = new ResultSetMapping();
$rsm->addEntityResult('MsoftRCSystemBundle:TbProduct', 'u');
$rsm->addFieldResult('u', 'id', 'id');
$rsm->addFieldResult('u', 'description', 'description');

$query = $this->createNativeQuery('SELECT * FROM tb_product WHERE quantity > 0 ?', $rsm);


$products = $query->getResult();
return $products;
    }
}
