Msoft\RCSystemBundle\Entity\TbCart:
    type: entity
    table: tb_cart
    indexes:
        id_shop:
            columns:
                - id_shop
        id_product:
            columns:
                - id_product
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        subtotal:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        dateIn:
            type: datetime
            nullable: true
            comment: ''
            column: date_in
        userIn:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_in
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        userUpdated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_updated
        removed:
            type: datetime
            nullable: true
            comment: ''
        userRemoved:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_removed
    manyToOne:
        idShop:
            targetEntity: TbShop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_shop:
                    referencedColumnName: id
            orphanRemoval: false
        idProduct:
            targetEntity: TbProduct
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_product:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
