Msoft\RCSystemBundle\Entity\TbEntry:
    type: entity
    table: tb_entry
    indexes:
        id_deliver:
            columns:
                - id_deliver
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        dateIn:
            type: datetime
            nullable: true
            comment: ''
            column: date_in
        userIn:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_in
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        userUpdated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_updated
        removed:
            type: datetime
            nullable: true
            comment: ''
        userRemoved:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_removed
    manyToOne:
        idDeliver:
            targetEntity: TbDeliver
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_deliver:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
