Msoft\RCSystemBundle\Entity\TbMethodPayment:
    type: entity
    table: tb_method_payment
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        type:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        dateIn:
            type: datetime
            nullable: true
            comment: ''
            column: date_in
        userIn:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_in
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        userUpdated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_updated
        removed:
            type: datetime
            nullable: true
            comment: ''
        userRemoved:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_removed
    lifecycleCallbacks: {  }
