Msoft\RCSystemBundle\Entity\TbPayment:
    type: entity
    table: tb_payment
    indexes:
        id_shop:
            columns:
                - id_shop
        id_method:
            columns:
                - id_method
        id_client:
            columns:
                - id_client
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        dateIn:
            type: datetime
            nullable: true
            comment: ''
            column: date_in
        userIn:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_in
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        userUpdated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_updated
        removed:
            type: datetime
            nullable: true
            comment: ''
        userRemoved:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_removed
    manyToOne:
        idClient:
            targetEntity: TbClient
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id
            orphanRemoval: false
        idShop:
            targetEntity: TbShop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_shop:
                    referencedColumnName: id
            orphanRemoval: false
        idMethod:
            targetEntity: TbMethodPayment
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_method:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
