Msoft\RCSystemBundle\Entity\TbShop:
    type: entity
    table: tb_shop
    indexes:
        id_client:
            columns:
                - id_client
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        pending:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        dateIn:
            type: datetime
            nullable: true
            comment: ''
            column: date_in
        userIn:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_in
        updatedDate:
            type: datetime
            nullable: true
            comment: ''
            column: updated_date
        updatedUser:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: updated_user
        removed:
            type: datetime
            nullable: true
            comment: ''
        removedUser:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: removed_user
    manyToOne:
        idClient:
            targetEntity: TbClient
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
