Msoft\RCSystemBundle\Entity\TbSubcategory:
    type: entity
    table: tb_subcategory
    indexes:
        id_category:
            columns:
                - id_category
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    manyToOne:
        idCategory:
            targetEntity: TbCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_category:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
