msoft_rc_system_homepage:
    path:     /
    defaults: { _controller: MsoftRCSystemBundle:Default:index }

   
tbsubcategory:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbsubcategory.yml"
    prefix:   /

tbproduct:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbproduct.yml"
    prefix:   /
   
tbcategory:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbcategory.yml"
    prefix:   /
   
tbdeliver:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbdeliver.yml"
    prefix:   /
   
tbentry:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbentry.yml"
    prefix:   /
    
tbstock:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbstock.yml"
    prefix:   /
    
tbclient:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbclient.yml"
    prefix:   /
    
tbmethodpayment:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbmethodpayment.yml"
    prefix:   /
    
tbcart:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbcart.yml"
    prefix:   /

tbpayment:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbpayment.yml"
    prefix:   /

tbshop:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/tbshop.yml"
    prefix:   /
    
    
PDV:
    resource: "@MsoftRCSystemBundle/Resources/config/routing/pdv.yml"
    prefix:   /
  
   